"""
Document Analysis Pipeline
文档批量分析流水线
"""

import os
import pandas as pd
from pathlib import Path
from datetime import datetime
from typing import List, Dict
import json
import re


class DocumentAnalyzer:
    """
    文档分析器
    批量处理文本文档
    """
    
    def __init__(self, input_dir: str, output_dir: str):
        """
        初始化分析器
        
        Args:
            input_dir: 输入目录
            output_dir: 输出目录
        """
        self.input_dir = Path(input_dir)
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        
        self.results = []
    
    def load_documents(self, extension: str = '.txt') -> List[Path]:
        """
        加载文档
        
        Args:
            extension: 文件扩展名
            
        Returns:
            文档路径列表
        """
        documents = list(self.input_dir.glob(f'*{extension}'))
        print(f"Found {len(documents)} documents")
        return documents
    
    def analyze_document(self, doc_path: Path) -> Dict:
        """
        分析单个文档
        
        Args:
            doc_path: 文档路径
            
        Returns:
            分析结果
        """
        try:
            with open(doc_path, 'r', encoding='utf-8') as f:
                text = f.read()
        except Exception as e:
            return {'error': str(e), 'file': str(doc_path)}
        
        # 基础统计
        word_count = len(text.split())
        char_count = len(text)
        sentence_count = text.count('.') + text.count('!') + text.count('?')
        
        # 词频分析
        words = text.lower().split()
        word_freq = pd.Series(words).value_counts().head(10).to_dict()
        
        # 可读性分数（简化）
        avg_word_length = sum(len(w) for w in words) / len(words) if words else 0
        readability_score = 100 - (avg_word_length * 5) - (sentence_count / max(word_count, 1) * 100)
        
        return {
            'file': str(doc_path),
            'filename': doc_path.name,
            'word_count': word_count,
            'char_count': char_count,
            'sentence_count': sentence_count,
            'avg_word_length': round(avg_word_length, 2),
            'readability_score': round(readability_score, 2),
            'top_words': word_freq,
            'analyzed_at': datetime.now().isoformat()
        }
    
    def analyze_all(self, extension: str = '.txt') -> pd.DataFrame:
        """
        分析所有文档
        
        Args:
            extension: 文件扩展名
            
        Returns:
            结果 DataFrame
        """
        documents = self.load_documents(extension)
        
        for doc_path in documents:
            print(f"Analyzing {doc_path.name}...")
            result = self.analyze_document(doc_path)
            self.results.append(result)
        
        df = pd.DataFrame(self.results)
        
        # 保存结果
        self.save_results(df)
        
        return df
    
    def save_results(self, df: pd.DataFrame):
        """保存分析结果"""
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        
        # CSV
        csv_path = self.output_dir / f'analysis_{timestamp}.csv'
        df.to_csv(csv_path, index=False, encoding='utf-8-sig')
        print(f"Saved CSV: {csv_path}")
        
        # JSON
        json_path = self.output_dir / f'analysis_{timestamp}.json'
        df.to_json(json_path, orient='records', force_ascii=False, indent=2)
        print(f"Saved JSON: {json_path}")
        
        # 汇总报告
        self.generate_summary_report(df)
    
    def generate_summary_report(self, df: pd.DataFrame):
        """生成汇总报告"""
        timestamp = datetime.now().strftime('%Y-%m-%d %H:%M')
        
        report = f"""
# Document Analysis Summary Report

**Generated**: {timestamp}

## Overview

- **Total Documents**: {len(df)}
- **Total Words**: {df['word_count'].sum():,}
- **Total Characters**: {df['char_count'].sum():,}
- **Average Word Count**: {df['word_count'].mean():,.0f}

## Statistics

| Metric | Min | Max | Mean | Median |
|--------|-----|-----|------|--------|
| Word Count | {df['word_count'].min()} | {df['word_count'].max()} | {df['word_count'].mean():.0f} | {df['word_count'].median():.0f} |
| Readability | {df['readability_score'].min():.1f} | {df['readability_score'].max():.1f} | {df['readability_score'].mean():.1f} | {df['readability_score'].median():.1f} |

## Top Documents by Word Count

{df.nlargest(5, 'word_count')[['filename', 'word_count']].to_markdown(index=False)}

---
*Report generated by Text Analytics Suite*
"""
        
        report_path = self.output_dir / f'summary_report_{datetime.now().strftime("%Y%m%d_%H%M%S")}.md'
        with open(report_path, 'w', encoding='utf-8') as f:
            f.write(report)
        print(f"Saved Report: {report_path}")


def demo_pipeline():
    """演示分析流水线"""
    print("=" * 60)
    print("Document Analysis Pipeline Demo")
    print("=" * 60)
    
    # 创建示例文档
    demo_dir = Path('./demo_documents')
    demo_dir.mkdir(exist_ok=True)
    
    sample_texts = [
        "Apple Inc. announced record quarterly earnings today. The tech giant's revenue exceeded analyst expectations.",
        "The Federal Reserve raised interest rates by 0.25% to combat inflation. Markets reacted positively to the decision.",
        "Tesla's new manufacturing facility in Texas will create thousands of jobs. Production is expected to begin next quarter."
    ]
    
    for i, text in enumerate(sample_texts, 1):
        doc_path = demo_dir / f'doc_{i}.txt'
        with open(doc_path, 'w', encoding='utf-8') as f:
            f.write(text)
    
    print(f"\nCreated {len(sample_texts)} demo documents")
    
    # 运行分析
    output_dir = Path('./demo_output')
    analyzer = DocumentAnalyzer(str(demo_dir), str(output_dir))
    
    print("\nRunning analysis...")
    df = analyzer.analyze_all('.txt')
    
    # 打印结果
    print("\n" + "=" * 60)
    print("Analysis Results")
    print("=" * 60)
    print(df[['filename', 'word_count', 'readability_score']].to_string(index=False))
    print("=" * 60)
    
    return df


if __name__ == "__main__":
    demo_pipeline()
